// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

public final class AdType {
  private AdType() { }
  public static final byte TEXT = 0;
  public static final byte VIDEO = 1;

  public static final String[] names = { "TEXT", "VIDEO", };

  public static String name(int e) { return names[e]; }
}

