// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AdxBidEntry extends Table {
  public static AdxBidEntry getRootAsAdxBidEntry(ByteBuffer _bb) { return getRootAsAdxBidEntry(_bb, new AdxBidEntry()); }
  public static AdxBidEntry getRootAsAdxBidEntry(ByteBuffer _bb, AdxBidEntry obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public AdxBidEntry __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public double bid() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public String bidder() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer bidderAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public AdxQuery adxQuery() { return adxQuery(new AdxQuery()); }
  public AdxQuery adxQuery(AdxQuery obj) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public double reservePrice() { int o = __offset(10); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createAdxBidEntry(FlatBufferBuilder builder,
      double bid,
      int bidderOffset,
      int adxQueryOffset,
      double reservePrice) {
    builder.startObject(4);
    AdxBidEntry.addReservePrice(builder, reservePrice);
    AdxBidEntry.addBid(builder, bid);
    AdxBidEntry.addAdxQuery(builder, adxQueryOffset);
    AdxBidEntry.addBidder(builder, bidderOffset);
    return AdxBidEntry.endAdxBidEntry(builder);
  }

  public static void startAdxBidEntry(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addBid(FlatBufferBuilder builder, double bid) { builder.addDouble(0, bid, 0.0); }
  public static void addBidder(FlatBufferBuilder builder, int bidderOffset) { builder.addOffset(1, bidderOffset, 0); }
  public static void addAdxQuery(FlatBufferBuilder builder, int adxQueryOffset) { builder.addOffset(2, adxQueryOffset, 0); }
  public static void addReservePrice(FlatBufferBuilder builder, double reservePrice) { builder.addDouble(3, reservePrice, 0.0); }
  public static int endAdxBidEntry(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

