// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

public final class Age {
  private Age() { }
  public static final byte Age_18_24 = 0;
  public static final byte Age_25_34 = 1;
  public static final byte Age_35_44 = 2;
  public static final byte Age_45_54 = 3;
  public static final byte Age_55_64 = 4;
  public static final byte Age_65_PLUS = 5;

  public static final String[] names = { "Age_18_24", "Age_25_34", "Age_35_44", "Age_45_54", "Age_55_64", "Age_65_PLUS", };

  public static String name(int e) { return names[e]; }
}

