// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AuctionReport extends Table {
  public static AuctionReport getRootAsAuctionReport(ByteBuffer _bb) { return getRootAsAuctionReport(_bb, new AuctionReport()); }
  public static AuctionReport getRootAsAuctionReport(ByteBuffer _bb, AuctionReport obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public AuctionReport __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public double firstBid() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double secondBid() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double reservePrice() { int o = __offset(8); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public AdxQuery adxQuery() { return adxQuery(new AdxQuery()); }
  public AdxQuery adxQuery(AdxQuery obj) { int o = __offset(10); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public short day() { int o = __offset(12); return o != 0 ? bb.getShort(o + bb_pos) : 0; }

  public static int createAuctionReport(FlatBufferBuilder builder,
      double firstBid,
      double secondBid,
      double reservePrice,
      int adxQueryOffset,
      short day) {
    builder.startObject(5);
    AuctionReport.addReservePrice(builder, reservePrice);
    AuctionReport.addSecondBid(builder, secondBid);
    AuctionReport.addFirstBid(builder, firstBid);
    AuctionReport.addAdxQuery(builder, adxQueryOffset);
    AuctionReport.addDay(builder, day);
    return AuctionReport.endAuctionReport(builder);
  }

  public static void startAuctionReport(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addFirstBid(FlatBufferBuilder builder, double firstBid) { builder.addDouble(0, firstBid, 0.0); }
  public static void addSecondBid(FlatBufferBuilder builder, double secondBid) { builder.addDouble(1, secondBid, 0.0); }
  public static void addReservePrice(FlatBufferBuilder builder, double reservePrice) { builder.addDouble(2, reservePrice, 0.0); }
  public static void addAdxQuery(FlatBufferBuilder builder, int adxQueryOffset) { builder.addOffset(3, adxQueryOffset, 0); }
  public static void addDay(FlatBufferBuilder builder, short day) { builder.addShort(4, day, 0); }
  public static int endAuctionReport(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

