// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Container extends Table {
  public static Container getRootAsContainer(ByteBuffer _bb) { return getRootAsContainer(_bb, new Container()); }
  public static Container getRootAsContainer(ByteBuffer _bb, Container obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Container __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public NewDay newDay() { return newDay(new NewDay()); }
  public NewDay newDay(NewDay obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public AdxBidList bidList() { return bidList(new AdxBidList()); }
  public AdxBidList bidList(AdxBidList obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static void startContainer(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addNewDay(FlatBufferBuilder builder, int newDayOffset) { builder.addStruct(0, newDayOffset, 0); }
  public static void addBidList(FlatBufferBuilder builder, int bidListOffset) { builder.addOffset(1, bidListOffset, 0); }
  public static int endContainer(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

