// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class DataBundle extends Table {
  public static DataBundle getRootAsDataBundle(ByteBuffer _bb) { return getRootAsDataBundle(_bb, new DataBundle()); }
  public static DataBundle getRootAsDataBundle(ByteBuffer _bb, DataBundle obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public DataBundle __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public AuctionReport reports(int j) { return reports(new AuctionReport(), j); }
  public AuctionReport reports(AuctionReport obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int reportsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createDataBundle(FlatBufferBuilder builder,
      int reportsOffset) {
    builder.startObject(1);
    DataBundle.addReports(builder, reportsOffset);
    return DataBundle.endDataBundle(builder);
  }

  public static void startDataBundle(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addReports(FlatBufferBuilder builder, int reportsOffset) { builder.addOffset(0, reportsOffset, 0); }
  public static int createReportsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startReportsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endDataBundle(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

