// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

public final class Device {
  private Device() { }
  public static final byte MOBILE = 0;
  public static final byte PC = 1;

  public static final String[] names = { "MOBILE", "PC", };

  public static String name(int e) { return names[e]; }
}

