// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

public final class Gender {
  private Gender() { }
  public static final byte Gender_MALE = 0;
  public static final byte Gender_FEMALE = 1;

  public static final String[] names = { "Gender_MALE", "Gender_FEMALE", };

  public static String name(int e) { return names[e]; }
}

