// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

public final class Income {
  private Income() { }
  public static final byte LOW = 0;
  public static final byte MEDIUM = 1;
  public static final byte HIGH = 2;
  public static final byte VERY_HIGH = 3;

  public static final String[] names = { "LOW", "MEDIUM", "HIGH", "VERY_HIGH", };

  public static String name(int e) { return names[e]; }
}

