// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

public final class MarketSegment {
  private MarketSegment() { }
  public static final byte MALE = 0;
  public static final byte FEMALE = 1;
  public static final byte YOUNG = 2;
  public static final byte OLD = 3;
  public static final byte LOW_INCOME = 4;
  public static final byte HIGH_INCOME = 5;

  public static final String[] names = { "MALE", "FEMALE", "YOUNG", "OLD", "LOW_INCOME", "HIGH_INCOME", };

  public static String name(int e) { return names[e]; }
}

