// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Messages extends Table {
  public static Messages getRootAsMessages(ByteBuffer _bb) { return getRootAsMessages(_bb, new Messages()); }
  public static Messages getRootAsMessages(ByteBuffer _bb, Messages obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Messages __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public Container messages(int j) { return messages(new Container(), j); }
  public Container messages(Container obj, int j) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int messagesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createMessages(FlatBufferBuilder builder,
      int messagesOffset) {
    builder.startObject(1);
    Messages.addMessages(builder, messagesOffset);
    return Messages.endMessages(builder);
  }

  public static void startMessages(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addMessages(FlatBufferBuilder builder, int messagesOffset) { builder.addOffset(0, messagesOffset, 0); }
  public static int createMessagesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMessagesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMessages(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishMessagesBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

