// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class NewDay extends Struct {
  public NewDay __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short day() { return bb.getShort(bb_pos + 0); }

  public static int createNewDay(FlatBufferBuilder builder, short day) {
    builder.prep(2, 2);
    builder.putShort(day);
    return builder.offset();
  }
}

