// automatically generated by the FlatBuffers compiler, do not modify

package tau.tac.adx.parser.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ReservePriceManagerBundle extends Table {
  public static ReservePriceManagerBundle getRootAsReservePriceManagerBundle(ByteBuffer _bb) { return getRootAsReservePriceManagerBundle(_bb, new ReservePriceManagerBundle()); }
  public static ReservePriceManagerBundle getRootAsReservePriceManagerBundle(ByteBuffer _bb, ReservePriceManagerBundle obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ReservePriceManagerBundle __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public AdxQueryPricing adxQueryPricings() { return adxQueryPricings(new AdxQueryPricing()); }
  public AdxQueryPricing adxQueryPricings(AdxQueryPricing obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createReservePriceManagerBundle(FlatBufferBuilder builder,
      int adxQueryPricingsOffset) {
    builder.startObject(1);
    ReservePriceManagerBundle.addAdxQueryPricings(builder, adxQueryPricingsOffset);
    return ReservePriceManagerBundle.endReservePriceManagerBundle(builder);
  }

  public static void startReservePriceManagerBundle(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addAdxQueryPricings(FlatBufferBuilder builder, int adxQueryPricingsOffset) { builder.addOffset(0, adxQueryPricingsOffset, 0); }
  public static int endReservePriceManagerBundle(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

