/**
 * 
 */
package tau.tac.adx.publishers.reserve;


/**
 * An extended {@link BasicReservePriceManager} which generates different reserve
 * prices for different types.
 * 
 * @author Tomer
 * 
 */
public interface MultiReservePriceManager<T> extends ReservePriceManager {
	
	/**
	 * @return A random reserve price according to the <b>daily baseline
	 *         average</b> and the <b>baseline range</b>.
	 */
	public double generateReservePrice(T t);

	/**
	 * Updates the {@link BasicReservePriceManager} with data about how many
	 * Impressions were generated by a given <b>reserve price</b>.
	 * 
	 * @param reservePrice
	 *            Reserve price to update data for.
	 */
	public void addImpressionForPrice(double reservePrice, T t);

	/**
	 * Updates the {@link #dailyBaselineAverage} in the direction of the reserve
	 * price that resulted in the highest profits during the day, according to
	 * the {@link #updateCoefficient}.<br>
	 * {@link #dailyBaselineAverage}= {@link #updateCoefficient} *
	 * dailyBaselineAverage + (1 - updateCoefficient) *
	 * highestProfitsReservePrice;
	 */
	public void updateData();

	/**
	 * @return the dailyBaselineAverage
	 */
	public double getDailyBaselineAverage(T t);

}
