package tau.tac.adx.publishers.reserve;

import tau.tac.adx.props.AdxQuery;

public interface ReservePriceManager {

	/**
	 * @return A random reserve price according to the <b>daily baseline
	 *         average</b> and the <b>baseline range</b>.
	 */
	public abstract double generateReservePrice(AdxQuery adxQuery);

	/**
	 * Updates the {@link BasicReservePriceManager} with data about how many
	 * Impressions were generated by a given <b>reserve price</b>.
	 * 
	 * @param reservePrice
	 *            Reserve price to update data for.
	 */
	public abstract void addImpressionForPrice(double reservePrice, AdxQuery adxQuery);

	/**
	 * Updates the internal data structure.
	 */
	public abstract void updateData();

}