# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auctions.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auctions.proto',
  package='',
  serialized_pb='\n\x0e\x61uctions.proto\"w\n\x08\x41\x64xQuery\x12\x11\n\tpublisher\x18\x01 \x02(\t\x12&\n\x0emarketSegments\x18\x02 \x03(\x0e\x32\x0e.MarketSegment\x12\x17\n\x06\x64\x65vice\x18\x03 \x02(\x0e\x32\x07.Device\x12\x17\n\x06\x61\x64type\x18\x04 \x02(\x0e\x32\x07.AdType\"i\n\rAuctionReport\x12\x10\n\x08\x66irstBid\x18\x01 \x02(\x01\x12\x12\n\nsecondsBid\x18\x02 \x02(\x01\x12\x15\n\rreservedPrice\x18\x03 \x02(\x01\x12\x1b\n\x08\x61\x64xQuery\x18\x04 \x02(\x0b\x32\t.AdxQuery\"-\n\nDataBundle\x12\x1f\n\x07reports\x18\x01 \x03(\x0b\x32\x0e.AuctionReport\"D\n\x0f\x41\x64xQueryPricing\x12\x1b\n\x08\x61\x64xQuery\x18\x01 \x02(\x0b\x32\t.AdxQuery\x12\x14\n\x0creservePrice\x18\x02 \x02(\x02\"G\n\x19ReservePriceManagerBundle\x12*\n\x10\x61\x64xQueryPricings\x18\x01 \x03(\x0b\x32\x10.AdxQueryPricing*Z\n\rMarketSegment\x12\x08\n\x04MALE\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x01\x12\t\n\x05YOUNG\x10\x02\x12\x07\n\x03OLD\x10\x03\x12\x0e\n\nLOW_INCOME\x10\x04\x12\x0f\n\x0bHIGH_INCOME\x10\x05*\x1c\n\x06\x44\x65vice\x12\n\n\x06MOBILE\x10\x00\x12\x06\n\x02PC\x10\x01*\x1d\n\x06\x41\x64Type\x12\x08\n\x04TEXT\x10\x00\x12\t\n\x05VIDEO\x10\x01\x42\x14\n\x12tau.tac.adx.parser')

_MARKETSEGMENT = _descriptor.EnumDescriptor(
  name='MarketSegment',
  full_name='MarketSegment',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MALE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YOUNG', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OLD', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOW_INCOME', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIGH_INCOME', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=436,
  serialized_end=526,
)

MarketSegment = enum_type_wrapper.EnumTypeWrapper(_MARKETSEGMENT)
_DEVICE = _descriptor.EnumDescriptor(
  name='Device',
  full_name='Device',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PC', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=528,
  serialized_end=556,
)

Device = enum_type_wrapper.EnumTypeWrapper(_DEVICE)
_ADTYPE = _descriptor.EnumDescriptor(
  name='AdType',
  full_name='AdType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIDEO', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=558,
  serialized_end=587,
)

AdType = enum_type_wrapper.EnumTypeWrapper(_ADTYPE)
MALE = 0
FEMALE = 1
YOUNG = 2
OLD = 3
LOW_INCOME = 4
HIGH_INCOME = 5
MOBILE = 0
PC = 1
TEXT = 0
VIDEO = 1



_ADXQUERY = _descriptor.Descriptor(
  name='AdxQuery',
  full_name='AdxQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='publisher', full_name='AdxQuery.publisher', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marketSegments', full_name='AdxQuery.marketSegments', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device', full_name='AdxQuery.device', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adtype', full_name='AdxQuery.adtype', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=137,
)


_AUCTIONREPORT = _descriptor.Descriptor(
  name='AuctionReport',
  full_name='AuctionReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstBid', full_name='AuctionReport.firstBid', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secondsBid', full_name='AuctionReport.secondsBid', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reservedPrice', full_name='AuctionReport.reservedPrice', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adxQuery', full_name='AuctionReport.adxQuery', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=139,
  serialized_end=244,
)


_DATABUNDLE = _descriptor.Descriptor(
  name='DataBundle',
  full_name='DataBundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reports', full_name='DataBundle.reports', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=246,
  serialized_end=291,
)


_ADXQUERYPRICING = _descriptor.Descriptor(
  name='AdxQueryPricing',
  full_name='AdxQueryPricing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adxQuery', full_name='AdxQueryPricing.adxQuery', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reservePrice', full_name='AdxQueryPricing.reservePrice', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=293,
  serialized_end=361,
)


_RESERVEPRICEMANAGERBUNDLE = _descriptor.Descriptor(
  name='ReservePriceManagerBundle',
  full_name='ReservePriceManagerBundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adxQueryPricings', full_name='ReservePriceManagerBundle.adxQueryPricings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=363,
  serialized_end=434,
)

_ADXQUERY.fields_by_name['marketSegments'].enum_type = _MARKETSEGMENT
_ADXQUERY.fields_by_name['device'].enum_type = _DEVICE
_ADXQUERY.fields_by_name['adtype'].enum_type = _ADTYPE
_AUCTIONREPORT.fields_by_name['adxQuery'].message_type = _ADXQUERY
_DATABUNDLE.fields_by_name['reports'].message_type = _AUCTIONREPORT
_ADXQUERYPRICING.fields_by_name['adxQuery'].message_type = _ADXQUERY
_RESERVEPRICEMANAGERBUNDLE.fields_by_name['adxQueryPricings'].message_type = _ADXQUERYPRICING
DESCRIPTOR.message_types_by_name['AdxQuery'] = _ADXQUERY
DESCRIPTOR.message_types_by_name['AuctionReport'] = _AUCTIONREPORT
DESCRIPTOR.message_types_by_name['DataBundle'] = _DATABUNDLE
DESCRIPTOR.message_types_by_name['AdxQueryPricing'] = _ADXQUERYPRICING
DESCRIPTOR.message_types_by_name['ReservePriceManagerBundle'] = _RESERVEPRICEMANAGERBUNDLE

class AdxQuery(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADXQUERY

  # @@protoc_insertion_point(class_scope:AdxQuery)

class AuctionReport(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUCTIONREPORT

  # @@protoc_insertion_point(class_scope:AuctionReport)

class DataBundle(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATABUNDLE

  # @@protoc_insertion_point(class_scope:DataBundle)

class AdxQueryPricing(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADXQUERYPRICING

  # @@protoc_insertion_point(class_scope:AdxQueryPricing)

class ReservePriceManagerBundle(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESERVEPRICEMANAGERBUNDLE

  # @@protoc_insertion_point(class_scope:ReservePriceManagerBundle)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\022tau.tac.adx.parser')
# @@protoc_insertion_point(module_scope)
