# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auctions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auctions.proto',
  package='',
  serialized_pb='\n\x0e\x61uctions.proto\"L\n\rAuctionReport\x12\x10\n\x08\x66irstBid\x18\x01 \x02(\x01\x12\x12\n\nsecondsBid\x18\x02 \x02(\x01\x12\x15\n\rreservedPrice\x18\x03 \x02(\x01\"-\n\nDataBundle\x12\x1f\n\x07reports\x18\x01 \x03(\x0b\x32\x0e.AuctionReport')




_AUCTIONREPORT = _descriptor.Descriptor(
  name='AuctionReport',
  full_name='AuctionReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstBid', full_name='AuctionReport.firstBid', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='secondsBid', full_name='AuctionReport.secondsBid', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reservedPrice', full_name='AuctionReport.reservedPrice', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=94,
)


_DATABUNDLE = _descriptor.Descriptor(
  name='DataBundle',
  full_name='DataBundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reports', full_name='DataBundle.reports', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=96,
  serialized_end=141,
)

_DATABUNDLE.fields_by_name['reports'].message_type = _AUCTIONREPORT
DESCRIPTOR.message_types_by_name['AuctionReport'] = _AUCTIONREPORT
DESCRIPTOR.message_types_by_name['DataBundle'] = _DATABUNDLE

class AuctionReport(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUCTIONREPORT

  # @@protoc_insertion_point(class_scope:AuctionReport)

class DataBundle(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATABUNDLE

  # @@protoc_insertion_point(class_scope:DataBundle)


# @@protoc_insertion_point(module_scope)
